version: "3.9"

services:
    db:
        image: mysql:5.7
        restart: always
        platform: linux/x86_64
        environment:
            - MYSQL_ROOT_PASSWORD=123123
            - MYSQL_DATABASE=contact-manager
        ports:
            - 3306:3306
        volumes:
            - contact-manager-mysql-data:/var/lib/mysql
            - contact-manager-mysql-config:/etc/mysql
    node-backend:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        platform: linux/x86_64
        environment:
            MYSQL_DBNAME: contact-manager
            MYSQL_USER: root
            MYSQL_PASSWORD: 123123
            MYSQL_HOST: db
        volumes:
            - ./:/laravel-hello
        ports:
            - "3030:3030"
        depends_on:
            - db

volumes:
    contact-manager-mysql-data:
    contact-manager-mysql-config:
